export const CALENDAR_DEFAULT_START_HOUR = 8;
export const CALENDAR_DEFAULT_END_HOUR = 18;
export const CALENDAR_HOUR_HEIGHT = 72;
export const CALENDAR_DRAG_SNAP_MINUTES = 15;
export const CALENDAR_MIN_SLOT_HEIGHT = 24;
export const CALENDAR_TIME_GUTTER_WIDTH = 84;
export const CALENDAR_DAY_MIN_WIDTH = 132;
