export const REGISTER_TEXT = {
  brand: "Clinic Portal",
  title: "Create your account",
  subtitle: "Patient registration takes only a moment.",
  fullNameLabel: "Full name",
  emailLabel: "Email",
  passwordLabel: "Password",
  confirmPasswordLabel: "Confirm password",
  submit: "Create patient account",
  loginPrompt: "Already have an account?",
  loginAction: "Sign in",
  fallbackError: "Unable to create your account. Please try again.",
  passwordRequirements: {
    minimumLength: "At least 8 characters",
    uppercase: "One uppercase letter",
    lowercase: "One lowercase letter",
    number: "One number",
    specialCharacter: "One special character",
  },
  validation: {
    fullNameRequired: "Full name is required.",
    fullNameMinimum: "Full name must be at least 2 characters.",
    fullNameMaximum: "Full name cannot exceed 100 characters.",
    emailRequired: "Email is required.",
    emailInvalid: "Enter a valid email address.",
    emailMaximum: "Email cannot exceed 150 characters.",
    passwordRequired: "Password is required.",
    passwordRequirements: "Password does not meet all requirements.",
    passwordMaximum: "Password cannot exceed 100 characters.",
    confirmPasswordRequired: "Please confirm your password.",
    passwordsMismatch: "Passwords do not match.",
  },
} as const;
